<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="css\styleGeral.css">

    </head>
    <body>
    <div>
        <button><a href="home_geral.php">Home</a></button>
        <button><a href="solicitarReserva.php">Solicitar Reserva</a></button>
        <button><a href="logout.php">Logout</a></button>
    </div>
    </body>
</html>



