<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="..\css\rodape_adm.css">
    </head>

    <body>
        <footer>
            <p>Endereço: Ten. José Joaquim - 1512, Vila Helena</p>
            <p><a href="politica_adm.php">Política de Privacidade</a> | <a href="termos_adm.php">Termos e Condições</a></p>
            &copy; 2023 SENAI - Todos os direitos reservados
        </footer>
    </body>
</html>